### ISSUE TITLE
Add UPDATE button near DELETE button

### ISSUE THREAD

**Issue by BioTech4Env** [BioTech4Env/WorkAutomation#1]
Along side the trash bin icon, there should be a button that updates the given row with new values.

##TODO

- [] Make row values editable on button click
- [] Write patch API on button
- [] Probably other tasks
